name: 32-bit MinGW builds
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || contains('joncampbell123', github.actor) == false
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: git mingw-w64-i686-toolchain mingw-w64-i686-libslirp mingw-w64-i686-libtool mingw-w64-i686-nasm autoconf automake
      - name: DOSBox-X MinGW32
        run: |
          top=`pwd`
          ln -s $top/build-scripts/mingw/make.exe /usr/bin/make.exe
          ./build-mingw
          strip --strip-all $top/src/dosbox-x.exe
          mkdir -p $top/package/mingw-build/mingw/drivez
          mkdir -p $top/package/mingw-build/mingw/scripts
          mkdir -p $top/package/mingw-build/mingw/shaders
          mkdir -p $top/package/mingw-build/mingw/glshaders
          mkdir -p $top/package/mingw-build/mingw/languages
          sed -e 's/^\(output[ ]*=[ ]*\)default$/\1ttf/' -e 's/^\(file access tries[ ]*=[ ]*\)0$/\13/' -e 's/^\(printoutput[ ]*=[ ]*\)png$/\1printer/' -e 's/\(drive data rate limit[ ]*=[ ]*\)-1$/\10/' $top/dosbox-x.reference.conf>$top/package/mingw-build/mingw/dosbox-x.conf
          cp $top/src/dosbox-x.exe $top/package/mingw-build/mingw/dosbox-x.exe
          cp $top/CHANGELOG $top/package/mingw-build/mingw/CHANGELOG.txt
          cp $top/dosbox-x.reference.conf $top/package/mingw-build/mingw/dosbox-x.reference.conf
          cp $top/dosbox-x.reference.full.conf $top/package/mingw-build/mingw/dosbox-x.reference.full.conf
          cp $top/contrib/windows/installer/readme.txt $top/package/mingw-build/mingw/README.txt
          cp $top/contrib/windows/installer/inpout32.dll $top/package/mingw-build/mingw/inpout32.dll
          cp $top/contrib/fonts/FREECG98.BMP $top/package/mingw-build/mingw/FREECG98.BMP
          cp $top/contrib/fonts/Nouveau_IBM.ttf $top/package/mingw-build/mingw/Nouveau_IBM.ttf
          cp $top/contrib/fonts/SarasaGothicFixed.ttf $top/package/mingw-build/mingw/SarasaGothicFixed.ttf
          cp $top/contrib/windows/installer/drivez_readme.txt $top/package/mingw-build/mingw/drivez/readme.txt
          cp $top/contrib/windows/installer/windows_explorer_context_menu*.bat $top/package/mingw-build/mingw/scripts/
          cp $top/contrib/windows/shaders/* $top/package/mingw-build/mingw/shaders/
          cp $top/contrib/glshaders/* $top/package/mingw-build/mingw/glshaders/
          for i in `ls $top/contrib/translations/` ; do cp $top/contrib/translations/$i/*.lng $top/package/mingw-build/mingw/languages/; done
          ./build-mingw-sdl2
          strip --strip-all $top/src/dosbox-x.exe
          mkdir -p $top/package/mingw-build/mingw-sdl2/drivez
          mkdir -p $top/package/mingw-build/mingw-sdl2/scripts
          mkdir -p $top/package/mingw-build/mingw-sdl2/shaders
          mkdir -p $top/package/mingw-build/mingw-sdl2/glshaders
          mkdir -p $top/package/mingw-build/mingw-sdl2/languages
          sed -e 's/^\(output[ ]*=[ ]*\)default$/\1ttf/' -e 's/^\(file access tries[ ]*=[ ]*\)0$/\13/' -e 's/^\(printoutput[ ]*=[ ]*\)png$/\1printer/' -e 's/\(drive data rate limit[ ]*=[ ]*\)-1$/\10/' $top/dosbox-x.reference.conf>$top/package/mingw-build/mingw-sdl2/dosbox-x.conf
          cp $top/src/dosbox-x.exe $top/package/mingw-build/mingw-sdl2/dosbox-x.exe
          cp $top/CHANGELOG $top/package/mingw-build/mingw-sdl2/CHANGELOG.txt
          cp $top/dosbox-x.reference.conf $top/package/mingw-build/mingw-sdl2/dosbox-x.reference.conf
          cp $top/dosbox-x.reference.full.conf $top/package/mingw-build/mingw-sdl2/dosbox-x.reference.full.conf
          cp $top/contrib/windows/installer/readme.txt $top/package/mingw-build/mingw-sdl2/README.txt
          cp $top/contrib/windows/installer/inpout32.dll $top/package/mingw-build/mingw-sdl2/inpout32.dll
          cp $top/contrib/fonts/FREECG98.BMP $top/package/mingw-build/mingw-sdl2/FREECG98.BMP
          cp $top/contrib/fonts/Nouveau_IBM.ttf $top/package/mingw-build/mingw-sdl2/Nouveau_IBM.ttf
          cp $top/contrib/fonts/SarasaGothicFixed.ttf $top/package/mingw-build/mingw-sdl2/SarasaGothicFixed.ttf
          cp $top/contrib/windows/installer/drivez_readme.txt $top/package/mingw-build/mingw-sdl2/drivez/readme.txt
          cp $top/contrib/windows/installer/windows_explorer_context_menu*.bat $top/package/mingw-build/mingw-sdl2/scripts/
          cp $top/contrib/windows/shaders/* $top/package/mingw-build/mingw-sdl2/shaders/
          cp $top/contrib/glshaders/* $top/package/mingw-build/mingw-sdl2/glshaders/
          for i in `ls $top/contrib/translations/` ; do cp $top/contrib/translations/$i/*.lng $top/package/mingw-build/mingw-sdl2/languages/; done
          cp $top/COPYING $top/package/COPYING
      - name: Upload release package
        uses: actions/upload-artifact@v2
        with:
          name: dosbox-x-mingw-win32
          path: ${{ github.workspace }}/package/
